initial_position:
  - 0.45
  - -0.10 
  - 0.45
  - 1.57
  - 0.0
  - 0.0

x_stride: 0.07
y_stride: 0.07
z_stride: 0.07

marker_size: 0.05 # in meter

sample_cube_size: 3 # Totally sampled points = size ^ 3

board_offset_x: 0
board_offset_y: 0
board_offset_z: 0

save_dir: /cali_data/
